image pe dash yellow transparent = "assets/effects/partial_effects/Dash-Effect.png"

image pe kick serangan_seiya = "assets/effects/partial_effects/Kick/Serangan-Seiya.png"
image pe kick serangan_seiya transparent  = "assets/effects/partial_effects/Kick/Serangan-seiya_Transparent.png"
image pe kick kick_set_alter = "assets/effects/partial_effects/Kick/Kick-Set_Alter.png"
image pe kick kick_set_alter transparent = "assets/effects/partial_effects/Kick/Kick-Set_Alter_Transparent.png"

image pe blue_meteor blash = "assets/effects/partial_effects/Projectile_Blast/Arc3_Scene14_Dityo_telah_tiba_dan_segera_menembakkan_serangan_proyektil_1.png"
image pe particle ring transparent = "assets/effects/partial_effects/Ring-Particle.png"
image pe blue_meteor ring = "assets/effects/partial_effects/Projectile_Blast/Arc3_Scene14_Dityo_telah_tiba_dan_segera_menembakkan_serangan_proyektil_2.png"
image pe blue_meteor full_CG = "assets/effects/partial_effects/Projectile_Blast/Arc3_Scene14_Dityo_telah_tiba_dan_segera_menembakkan_serangan_proyektil_FullCG.png"

image pe red_blast transparent = "assets/effects/partial_effects/Particle-Red-Blast.png"
image pe red_blast gradient = "assets/effects/partial_effects/Gradient.png"
image pe red_blast full_CG = "assets/effects/partial_effects/Projectile_Zoom/Arc3_Scene16_sebuah_pusaran_energi_melesat_mengarah_langsung_padanya_FullCG.png"

image pe continuous_attack line_of_action = "assets/effects/partial_effects/Continuous_Attack/Arc3_Scene14_Akasyah_mulai_menghantam_Seiya_dengan_tinju_dan_tendangan_Line_of_Action.png"
image pe continuous_attack attack_bottom transparent = "assets/effects/partial_effects/Continuous_Attack/Arc3_Scene14_Akasyah_mulai_menghantam_Seiya_dengan_tinju_dan_tendangan_1.png"
image pe continuous_attack attack_left transparent = "assets/effects/partial_effects/Continuous_Attack/Arc3_Scene14_Akasyah_mulai_menghantam_Seiya_dengan_tinju_dan_tendangan_2.png"
image pe continuous_attack attack_right transparent = "assets/effects/partial_effects/Continuous_Attack/Arc3_Scene14_Akasyah_mulai_menghantam_Seiya_dengan_tinju_dan_tendangan_3.png"
image pe continuous_attack full_CG = "assets/effects/partial_effects/Continuous_Attack/Arc3_Scene14_Akasyah_mulai_menghantam_Seiya_dengan_tinju_dan_tendangan_Full_Effect.png"

image pe blue_projectile ball_1 transparent = "assets/effects/partial_effects/Projectile_BALLS_Blue/Arc3_Scene15_Dia_melempar_banyak_sekali_bola_1.png"
image pe blue_projectile ball_2 transparent = "assets/effects/partial_effects/Projectile_BALLS_Blue/Arc3_Scene15_Dia_melempar_banyak_sekali_bola_2.png"
image pe blue_projectile ball_3 transparent = "assets/effects/partial_effects/Projectile_BALLS_Blue/Arc3_Scene15_Dia_melempar_banyak_sekali_bola_3.png"
image pe blue_projectile ball_4 transparent = "assets/effects/partial_effects/Projectile_BALLS_Blue/Arc3_Scene15_Dia_melempar_banyak_sekali_bola_4.png"
image pe blue_projectile ball_5 transparent = "assets/effects/partial_effects/Projectile_BALLS_Blue/Arc3_Scene15_Dia_melempar_banyak_sekali_bola_5.png"
image pe blue_projectile ball_6 transparent = "assets/effects/partial_effects/Projectile_BALLS_Blue/Arc3_Scene15_Dia_melempar_banyak_sekali_bola_6.png"
image pe blue_projectile all_balls transparent = "assets/effects/partial_effects/Projectile_BALLS_Blue/Arc3_Scene15_Dia_melempar_banyak_sekali_bola_Mass_Balls.png"
image pe dash blue = "assets/effects/partial_effects/Dash-Blue_or_Roar.png"
image pe blue_projectile full_CG = "assets/effects/partial_effects/Projectile_BALLS_Blue/Arc3_Scene15_Dia_melempar_banyak_sekali_bola_Full_CG.png"

image pe red_projectile ball_1 transparent = "assets/effects/partial_effects/Projectile_Balls_BLACK/Arc3_Scene16_Serangan_proyektil_hitam_1.png"
image pe red_projectile ball_2 transparent = "assets/effects/partial_effects/Projectile_Balls_BLACK/Arc3_Scene16_Serangan_proyektil_hitam_5.png"
image pe red_projectile ball_3 transparent = "assets/effects/partial_effects/Projectile_Balls_BLACK/Arc3_Scene16_Serangan_proyektil_hitam_3.png"
image pe red_projectile ball_4 transparent = "assets/effects/partial_effects/Projectile_Balls_BLACK/Arc3_Scene16_Serangan_proyektil_hitam_4.png"
image pe red_projectile ball_5 transparent = "assets/effects/partial_effects/Projectile_Balls_BLACK/Arc3_Scene16_Serangan_proyektil_hitam_2.png"
image pe red_projectile ball_6 transparent = "assets/effects/partial_effects/Projectile_Balls_BLACK/Arc3_Scene16_Serangan_proyektil_hitam_6.png"
image pe red_projectile all_balls transparent = "assets/effects/partial_effects/Projectile_Balls_BLACK/Arc3_Scene16_Serangan_proyektil_hitam_Mass_BALLS.png"
image pe dash negative_blue = "assets/effects/partial_effects/Dash-Negative.png"
image pe red_projectile full_CG = "assets/effects/partial_effects/Projectile_Balls_BLACK/Arc3_Scene16_Serangan_proyektil_hitam_Mass_BALLS_Full_CG.png"

image pe swing dawam = "assets/effects/partial_effects/Swing/Revisi/Arc3_Scene16_Dawam_Menghantam.png"
image pe swing dawam transparent = "assets/effects/partial_effects/Swing/Revisi/Arc3_Scene16_Dawam_Menghantam_Transparent.png"
# image pe swing "assets/effects/partial_effects/Swing/Arc3_Scene16_Dawam_Menghantam.png"
# image pe swing "assets/effects/partial_effects/Swing/Arc3_Scene16_Dawam_Menghantam_Transparent.png"

image pe purple_flame front = "assets/effects/partial_effects/Fire/Arc2_Scene11_Api_kemudian_membakar_Axiaregis_Front.png"
image pe purple_flame behind = "assets/effects/partial_effects/Fire/Arc2_Scene11_Api_kemudian_membakar_Axiaregis_Behind.png"
image pe purple_flame full = "assets/effects/partial_effects/Fire/Arc2_Scene11_Api_kemudian_membakar_Axiaregis_Full.png"

# "assets/effects/partial_effects/Punch/Punch_1/Arc2_Scene9_Tangan_melesat_kepadaku.png"
# "assets/effects/partial_effects/Punch/Punch_1/Arc2_Scene9_Tangan_melesat_kepadaku_Transparent.png"
image pe punch yellow = "assets/effects/partial_effects/Punch/Revision/Arc2_Scene9_Sebuah_tangan_melesat_ke_arahku.png"
image pe punch yellow transparent = "assets/effects/partial_effects/Punch/Revision/Arc2_Scene9_Sebuah_tangan_melesat_ke_arahku_Transparent.png"
image pe punch swipe = "assets/effects/partial_effects/Punch/Punch_2/Arc2_Scene9_Tangan_melesat_kepadaku_Alternative.png"
image pe punch swipe transparent = "assets/effects/partial_effects/Punch/Punch_2/Arc2_Scene9_Tangan_melesat_kepadaku_Alternative_Transparent.png"
image pe punch purple transparent = "assets/effects/partial_effects/Punch/Revision/BLACK_FORCE_ENERGY/Punch_Set-Alter_Dark.png"
