# label start:

label scene_17:

    # show penginapan yozakura
    # play music pria asing
    "Sementara itu di tempat yang tidak diketahui, aku terbangun tepat di hadapan seseorang yang pernah kutemui di dalam hutan."
    y "Dimana aku ? Kenapa aku disini ?"
    pria "Ah... Sang putri tidur sudah bangun."
    pria "Selamat datang kembali di rumah."
    "Aku mundur beberapa langkah setelah mendengar suara itu."
    pria "Ada apa ? kenapa kamu terlihat sangat terkejut melihatku ?"
    pria "Bukankah kau yang mengajakku untuk minum teh bersama ?"
    y "Minum teh ?"
    "Aku melihat sekeliling dan mendapati diriku berada di kamar tempat pertama kali aku bangun, tapi suasananya jauh berbeda dari sebelumnya."
    "Belum lagi peralatan minum serta pria asing yang tiba-tiba ada di kamar ini membuatnya jadi lebih membingungkan."
    y "(Tunggu... Bukannya aku sebelumnya berada di halaman belakang tempat ini...)"
    y "Bagaimana aku bisa disini ?"
    y "Apa yang terjadi ? Bukankah tadi ada pertarungan ?"
    "Pria itu tertawa kecil."
    pria "Pertarungan ? Apa maksudmu ?"
    pria "Bukankah kita disini untuk membicarakan dirimu ?"
    y "Diri...ku ???"
    pria "Ya... Aku ingin membicarakan soal dirimu."
    y "Hah ?"
    "Yuura menggelengkan kepala ke samping."
    "Aku sedikit bingung melihat tingkah pria asing itu, membuatku semakin mempertanyakan apa maksud dari semua ini."
    pria "Langit benar-benar sudah menentukan takdirnya sendiri."
    pria "Sudah banyak sekali takdir yang tertulis, namun hanya satu yang benar."
    pria "Sekarang giliranmu, Aneeki."
    "Yuura menyemburkan teh yang baru ia teguk."
    "..."
    y "Ah maaf..."
    pria "Hahahaha... Sungguh suatu hal yang tak terduga bukan ?"
    "Pria itu menjentikkan jari nya dan seketika sisa-sisa teh yang ada di tubuhnya lenyap seperti tak terjadi apa-apa."
    y "Bagaimana..."
    pria "Ssttt kita tidak akan berfokus pada itu sekarang."
    pria "Takdirmu sudah ditentukan sejak awal."
    pria "Sekarang ini adalah waktunya untukmu memilih."
    # stop music
    menu siap:
        "Aku belum siap":
            # play music pria asing
            y "Aku belum siap."
            pria "Tidak apa, biar aku tunjukkan sesuatu untukmu."
            "Pria itu menjentikkan jarinya dan membuat kami langsung berpindah menuju sebuah ruangan putih yang tak aku kenali sama sekali."
            # play sound zupp
            # show ruang putih
            y "D-dimana kita sekarang ?"
            pria "Kita ada di dalam pusat alam bawah sadar mu."
            y "!?"
            "Pria itu tertawa kecil."
            pria "Semakin aku lihat kamu semakin imut saja"
            y "Berhenti bercanda sekarang juga ! Apa sih yang ingin kamu sampaikan ?"
            pria "Kenapa terlalu terburu-buru seperti itu ?"
            pria "Apa kamu tidak nyaman berbicara denganku ?"
            y "DIEM !"
            pria "Hahaha memang dirimu tidak pernah berubah ya, Aneeki."
            pria "Selalu saja terburu-buru, apalagi jika kita bahas soal sake."
            pria "Apa kamu ingat ? Ketika hari itu kamu pulang dengan satu buah box berisi sake ?"
            "Tiba-tiba saja muncul penglihatan di ruangan putih itu mengenai kenangan ketika aku berpesta dengan mereka. Canda dan tawa terdengar jelas di telingaku, seakan-akan aku masuk kedalamnya."
            pria "Kita bernyanyi dari pagi, tanpa memikirkan apakah besok kita punya kegiatan atau tidak."
            pria "Kamu bahkan yang paling lantang dalam mengajak kami semua minum."
            pria "Rasanya sangat menyenangkan bukan ? Melihat mereka tertawa dan tersenyum."
            y "Aku... Tidak mengerti..."
            pria "Tidak apa, tidak semua hal harus dipahami."
            pria "Tapi rasakanlah kenangannya dalam benakmu."
            y "..."
            y "Aku..."
            pria "Tidak perlu memaksakan dirimu, ada aku yang siap membantumu selalu."
            pria "Bagaimana jika kita lanjutkan saja ?"
            "Pria itu menampilkan sebuah momen ketika aku membacakan sebuah cerita pada mereka, pembawaanku yang tadinya kasar dan beringas menjadi sangat lembut."
            "Mereka terlihat nyaman mendengar suaraku yang menenangkan hati, membuat mereka perlahan tertidur pulas."
            pria "Suara yang indah dan menenangkan."
            pria "Bahkan dunia pun terlelap mendengar suaranya."
            pria "Dongeng yang selalu dibuat oleh teman-teman."
            pria "Dan dibacakan oleh sang dewi."
            pria "Sungguh perpaduan yang indah, bukan ?"
            "Aku semakin bingung, sejak kapan aku pernah membacakan mereka cerita. Aku tidak paham arah dari pembicaraan ini."
            y "Bisakah kita berhenti ?"
            pria "Mengapa demikian ?"
            y "Aku... Aku tak pernah melakukan yang kamu sebutkan..."
            y "Aku bukan Yuura yang kalian kenal."
            "Pria itu tersenyum, dia menatapku dengan penuh kasih. Rasanya sangat menenangkan melihatnya."
            pria "Jadi... Kamu Yuura yang mana ?"
            y "Apa maksudmu ?"
            pria "Yuura yang belum melunasi hutangnya ?"
            pria "Atau Yuura yang akan selalu tersenyum untuk kami ?"
            pria "Atau Yuura yang akan selalu bernyanyi bersama kami ?"
            pria "Atau Yuura yang akan selalu tertawa bersama kami ?"
            y "Aku tidak mengerti apa yang kamu ingin sampaikan ?"
            y "Aku bukanlah Yuura yang kamu kenal ! Aku terlempar kesini dan menjalani hari yang super berat."
            y "Apakah kita tidak bisa berhenti saja ?"
            "Mendengar kata itu, membuatnya terdiam sejenak. Dia menatap langit-langit sembari tersenyum kecil."
            pria "Apa kamu pernah terpikirkan perasaan mereka yang menyerangmu ?"
            y "Tidak ! Mana mungkin aku mau memikirkan orang-orang aneh seperti mereka ?"
            pria "Kenapa ?"
            y "Ya... Buat apa? Kenapa aku harus peduli sama kalian ?"
            y "Tempatku bukan disini... Aku tak memiliki tempat di sini dan tak akan pernah."
            pria "Apakah kamu yakin dengan itu ?"
            y "Iyalah..."
            pria "Baiklah... Biar aku perlihatkan sesuatu untukmu."
            "Pria itu memperlihatkan beberapa foto lainnya, di mana momen ketika semua orang merayakan ulang tahunku."
            "Mereka terlihat dengan bersemangat membuat hal-hal diluar nalar, membuatku mempertanyakan mengapa mereka begitu peduli padaku ?"
            pria "Bagaimana ? Apa ada sesuatu yang berbeda ?"
            y "Aku... Aku tak bisa..."
            y "Aku tak bisa seperti Yuura yang lama, aku tak bisa... Sama sekali tidak bisa."
            y "Aku berbeda ! Aku tidak bisa menjadi orang lain !"
            pria "Siapa yang menyuruhmu menjadi seperti Yuura yang lama ?"
            pria "Apakah kamu pikir Yuura yang dulu seperti gambar itu ?"
            pria "Apa kamu kira dia sempurna sejak awal ?"
            "Pria Itu tersenyum, tangannya yang lembut mengelus pipiku dan menyeka air mataku."
            pria "Yuura perlu waktu yang lama untuk bisa di tempat ini."
            pria "Dia tidak pernah menyerah, selalu berusaha yang terbaik."
            pria "Bahkan terkadang dia akan memaksakan dirinya sendiri."
            pria "Apakah kamu pikir dia berubah karena orang-orang ingin dia berubah ?"
            pria "Tidak... Dia berubah karena dirinya sendiri, dia selalu menjadi dirinya sendiri."
            pria "Untuk apa dirimu berusaha menjadi Yuura yang dulu ?"
            pria "Untuk siapa ? Dan kenapa kamu harus ?"
            pria "Demi kebahagiaan kita ? PPFFTT HAHAHAHA !"
            pria "Melihatmu tersenyum saja sudah sangat membahagiakan bagi kami."
            pria "Jadi... Berhenti memaksakan dirimu."
            pria "Jadilah dirimu sendiri dan temukan jati dirimu sendiri."
            pria "Karena Yuura yang ku kenal adalah orang yang kuat" # kasih pause setelah kata "kenal"?
            pria "Jadi jangan menangis... Tersenyumlah dan berbahagialah !" # kasih pause setelah jeda titik-titik?
            "Pria itu menjentikkan jarinya, perlahan memperlihatkan dua buah pintu untukku."
            pria "Takdir memanglah kejam, dia tak memberikan waktu untukmu."
            pria "Yang kau bisa lakukan adalah memilih."
            pria "Jadilah Yuura yang kamu inginkan atau pergi dan tak pernah kembali."
            menu keputusan:
                "Pergi dari Inn untuk selamanya":
                    # play music foto foto kenangan
                    y "Aku tak bisa."
                    pria "Mengapa ?"
                    y "Aku rasa... Aku bukan lah orang yang cocok."
                    pria "Apa maksudmu, anee ?"
                    pria "Mengapa kamu berbicara seperti itu ?"
                    y "Aku... Hanya tidak mengerti mengapa aku harus di sini..."
                    y "Memang benar banyak hal yang terjadi hari ini."
                    y "Memang benar semua yang kamu beritahukan padaku sungguh indah."
                    y "Tapi itu bukanlah diriku..."
                    y "Aku tak pernah melakukan semua itu..."
                    y "Aku merasa tidak pantas untuk menggantikan Yuura kalian."
                    y "Bahkan aku saja jauh dari Yuura yang kalian kenal."
                    y "Aku... Hanya ingin pulang, ke tempat asalku..."
                    pria "..."
                    y "..."
                    "Aku benar-benar terdiam, tak tahu harus berbuat apa lagi. Aku hanya ingin beristirahat dan melupakan semua kejadian yang melelahkan ini."
                    pria "Baiklah..."
                    pria "Aku memang tak bisa memaksakan keputusan mu..."
                    pria "Hahaha... Rasanya sangat menyakitkan yah..."
                    y "Maaf... Aku tidak punya pilihan lagi."
                    pria "Tak apa... Aku mengerti."
                    pria "Pada akhirnya sang pengembara pun harus berpisah dengan kota yang ia singgahi bukan ?"
                    pria "Tapi, meskipun begitu aku harap kamu tetap kembali pada kami."
                    pria "Karena kami akan selalu ada di sini untukmu."
                    pria "Maaf jika selama ini kami selalu merepotkanmu."
                    pria "Maaf jika kami tidak bisa menjadi orang yang baik untukmu."
                    pria "Kalau begitu sampai jumpa."
                    pria "Semoga takdir dunia ini mempertemukan kami denganmu kembali."
                    y "Terimakasih... {w}Yuuraid."
                    "Aku terbangun tepat di hadapan orang-orang yang sudah tidak sadarkan diri, hujan mulai turun menutupi langit yang cerah."
                    "Semuanya menjadi sangat kelabu dan menyakitkan, aku berjalan melewati semua orang dan pergi keluar penginapan ini."
                    "Tanpa melihat ke belakang dan tanpa menyesali semuanya. Aku harap aku tak akan kembali kesini, meskipun hatiku masih menginginkannya."
                    # ------------ END ------------
                "Yuuraid adalah segalanya bagiku":
                    # play music two chords
                    y "Aku..."
                    y "Aku tidak mengerti... Sama sekali tidak mengerti dengan ini semua..."
                    y "Mengapa kalian melakukan semua ini hanya demi diriku ?"
                    y "Maksudku... Ah ! Apasih..."
                    "Air mataku turun perlahan, tidak mengerti mengapa semuanya terjadi. Mengapa semua orang mengejarku dan mengapa ada orang yang ingin melindungiku. Aku sungguh tidak mengerti apa-apa."
                    "Sampai sekarang pun aku hanya melarikan diri, tanpa memahami apa-apa."
                    y "Apa sih yang kalian lakukan..."
                    y "Apa kalian tidak takut bahwa aku akan pergi meninggalkan kalian ?"
                    y "Apa kalian tidak takut ketika aku berubah menjadi seseorang yang kalian tidak kenali ?"
                    y "KENAPA KALIAN MELAKUKAN INI ?"
                    y "Kenapa kalian ga bisa melupakan diriku saja ? Kenapa kalian memaksaku, mengejarku bahkan berusaha menangkapku ?"
                    pria "Jika kamu bertanya padaku."
                    pria "Alasannya simple, karena kamu Yuura." # kasih pause setelah jeda koma?
                    pria "Karena mereka peduli padamu, pada Yuura." # kasih pause setelah jeda koma?
                    y "Tapi aku bukan Yuura yang kalian kenal !"
                    y "Mengapa masih saja ada yang mau melindungiku, bahkan melukai dirinya sendiri demi diriku !"
                    pria "Karena kamu Yuura."
                    y "Bagaimana bisa ? Hanya karena aku mirip dengan orang yang kalian kenal, kalian langsung melakukan apapun demiku !" # demiku atau demi aku?
                    y "Apa kalian itu tolol atau gimana sih !"
                    pria "Pffttt !!"
                    pria "Hahaha"
                    y "Apanya yang lucu dari itu ?"
                    pria "Tidak... Hanya saja itu adalah hal yang paling sering kamu katakan."
                    y "Maksudmu ?"
                    pria "Iya... Kamu selalu bilang "Yuuraid itu aneh banget, emang kalian ga cape apa ?"" # italic buat kutipannya kah?
                    pria "Tapi kita selalu bilang "ga, biasa aja sih"" # perlukah italic?
                    pria "Terus kita ketawa bareng-bareng."
                    pria "Lagian, untuk apa kamu bertanya hal itu ?"
                    pria "Kami ngelakuin semua ini, ya karena kamu !"
                    "Aku semakin bingung dengan pernyataan yang pria ini lontarkan. Aku tak mengerti mengapa dia terlihat tidak peduli, padahal aku adalah orang asing."
                    pria "Biar aku tunjukkan padamu."
                    # stop music
                    # play misic credit scene
                    "Pria itu menunjukkan sebuah video, di mana banyak hal yang terjadi."
                    pria "Bagaimana menurutmu ?"
                    pria "Apa kamu masih ragu pada dirimu sendiri ?"
                    y "..."
                    pria "Tidak apa, untuk sekarang kembalilah dan temui mereka."
                    pria "Katakan bahwa kamu adalah Yuura."
                    pria "Baik Yuura yang manapun itu, kamu tetaplah Yuura."
                    pria "Selesaikan semuanya, dan jadilah dirimu sendiri."
                    pria "Jadilah Yuura yang kami sayangi, kami cintai dan kami dukung."
                    "Perlahan aku mulai menghilang, melihat Pria itu tersenyum bahagia membuatku merasa sangat bahagia. Apakah ini adalah jalan yang benar untukku? Entahlah, aku hanya perlu menjadi diriku sendiri."
                    y "Terimakasih... Risol."
                    pria "Kau salah... Aku adalah Yuuraid." # kasih pause setelah jeda titik-titik?
                    y "Ya ! Terimakasih, Yuuraid."
                    "Aku menghilang sepenuhnya dan kembali ke dunia nyata."
                    jump scene_18
        "Aku ingin pergi dari sini":
            # play music foto foto kenangan
            y "Aku ingin pergi dari sini."
            pria "Apa kamu yakin dengan pilihan mu ?"
            y "Maaf... Aku tidak bisa disini..."
            pria "kamu orang yang seperti itu ya."
            y "Maaf…..."
            pria "Untuk apa minta maaf ?"
            pria "Tidak ada yang salah dalam pilihan mu."
            y "Maaf… aku bukan orang yang baik."
            pria "Tidak apa, tidak semua orang berani mengambil pilihan."
            pria "Pada akhirnya sang pengembarapun harus berpisah dengan kota yang ia singgahi bukan ?"
            pria "Tapi, meskipun begitu aku harap kamu tetap kembali pada kami."
            pria "Karena kami akan selalu ada di sini untukmu."
            pria "Maaf jika selama ini kami selalu merepotkanmu."
            pria "Maaf jika kami tidak bisa menjadi orang yang baik untukmu."
            pria "Kalau begitu sampai jumpa."
            pria "Semoga takdir dunia ini mempertemukan kami denganmu kembali."
            y "Terimakasih...{w} Yuuraid."
            "Aku terbangun tepat di hadapan orang-orang yang sudah tidak sadarkan diri, hujan mulai turun menutupi langit yang cerah."
            "Semuanya menjadi sangat kelabu dan menyakitkan, aku berjalan melewati semua orang dan pergi keluar penginapan ini."
            "Tanpa melihat ke belakang dan tanpa menyesali semuanya. Aku harap aku tak akan kembali ke sini, meskipun hatiku masih menginginkannya."
            # ------------ END ------------
    return