# label start:

label scene_15:

    # show lorong penginapan with Dissolve(1.0)
    y "Ah... Ah..."
    "Aku sudah berlari lumayan jauh dari lorong tempat mereka bertarung satu sama lain, aku sedikit heran, mengapa mereka berani untuk bertarung satu sama lain... Karena aku ?"
    "Tapi sebelum sempat berpikir lebih jauh, aku merasa ada seorang yang mendekat ke arahku."
    y "Ahh... Aku capek..."
    "Tiba-tiba aku merasakan ada seseorang yang memelukku dari belakang, dia berbisik pelan di telingaku, suaranya membuat bulu kudukku merinding ketakutan."
    u "Anyeeeee kamu ngapain disini sendirian ??"
    y "KYAHHHH !"
    # play sound perempuan teriak
    "Aku melayangkan tanganku ke arahnya, berharap ia per-"
    y "WHAT THE FAHHH ?!"
    y "(T-TUBUHNYA.. TERBELAH !?)"
    "Dia tersenyum kecil sebelum tubuhnya menghilang seperti tertiup angin. Suasana di sekitar menjadi suram hingga entah darimana, dia tiba-tiba muncul kembali di hadapanku."
    axia "Arere ? Kenyapa kamu kaget begituh ?"
    axia "Tidak usah takut anyee, ini aku, Axiaregis. Aku di sini untukmu."
    "Dia mengulurkan tangannya, membuat diriku semakin takut padanya."
    y "Pergi ! PERGI !"
    axia "Kenapa kamu selalu mengusirku sih ?"
    axia "Apa aku memang tidak berhak ada di sekitarmu ?"
    y "M-menjauhlah dariku !"
    "Gadis dengan suara om-om itu pun mulai berjalan membelakangiku. Yang entah mengapa, semakin ia menjauh dariku, suasana di sini malah terasa sesak."
    axia "Kenapa sihhh harus selalu akuhhh yang pergi ?"
    y "Kamu aneh ! Aku sudah lelah dengan semua keanehan ini."
    axia "Begitukah ?"
    y "Sial ! Keknya aku salah ngomong lagi."
    "Gadis itu tiba-tiba tersenyum dan mulai mendekatiku kembali. Dan ketika ia mendekat, suasana di sepanjang lorong ini makin terasa sesak."
    axia "Bagaimana nihhh, padahal aku pengen banget main sama kamu."
    axia "Kalau bisa... AKU INGIN MEMILIKI MU SELAMANYA !"
    axia "Seperti sebuah Standee yang ada di pojok ruangan !"
    axia "Memandangiku dan selalu tersenyum padaku !"
    axia "Are ? Kamu kenapa berkeringat anyee ? Aku hanya bercanda kok..."
    axia "Or... I'm ?" # im atau I'm nih?
    # show yuura takut shake 
    y "*Tersentak"
    "Tubuhku tak dapat bergerak tepat setelah menatap mata Axiaregis yang menyala, aku mencoba menggerakkan seluruh anggota tubuh, namun hasilnya nihil. Aku tetap tak bisa bergerak, sementara nafasku perlahan mulai tersengal."
    axia "Oh... Anyeeki yang malang~ Aku sungguh kasihan padamu."
    axia "Bagaimana jika kamu menyerah saja ?"
    axia "Jika kamu menyerah semuanya akan menjadi lebih baik loh~"
    menu lawan:
        "Menyerah pada Axiaregis":
            y "A-aku... menyerah !"
            axia "Begitukah ? Sayang sekali kamu harus mati kalau begitu..."
            y "Hah ? Kenapa begitu ?"
            axia "Simple saja, Yuura yang ku kenal tak mungkin menyerah begitu saja"
            axia "Selamat tinggal..."
            # show black with Dissolve(1.0)
            "Axiaregis menjentikkan jarinya dan membuatku mematung tak bisa bergerak, mataku menjadi blur dan semuanya menjadi tak terlihat lagi. Aku mematung untuk selamanya."
            # end?
        "Berontak sekuat tenaga":
            y "ARGhhh Lepas !"
            axia "Ihhh anyeee semakin imut deh kalau terus ngelawan kayak gitu."
            axia "Tapi sayangnya semuanya akan sia-sia saja."
            u "Tidak jika aku membantu ! Aku keluarkan kartuku, {w}Fathanil !!!!"
            axia "Huh ?"
            # play sound kucing huh
            "Tiba-tiba saja muncul sebuah kudanil besar menabrakkan dirinya yang membuat Axiaregis terpental ke dalam ruangan."
            axia "Ah…... Iya-iya si penjaga hewan rupanya..."
            rian "Aku bukan penjaga hewan, aku adalah sang petualang yang hanya numpang lewat. Ingat itu !"
            rian "Namaku, Rian !"
            axia "Ha... Sungguh menyebalkan sekali rasanya."
            axia "Padahal aku ingin banget bersama Yuura ku !"
            axia "Tapi kamu mengganggu semuanya !"
            rian "Nenekku pernah berkata."
            rian "Jangan berani kamu lukai hati seorang wanita !"
            rian "Kalau kamu tetap melakukannya, maka aku akan menghajarmu !"
            axia "Ahhhh berisik berisik berisik!"
            axia "Ayo kita bertarung."
            rian "Oke, ayo kita duel !"
            "Axiaregis menggunakan kekuatannya untuk merubah tempat ini jadi arena battle."
            # show duel arena yugioh
            axia "Sekarang giliranku."
            axia "Aku Summon Renge dengan attack 300 ke arena !"
            axia "Aku aktifkan efeknya! Mengikat kuda nil mu ke posisi bertahan."
            rian "Sial... Aku aktifkan efek Fatanil !"
            rian "Ketika dia bertahan, Fatanil akan menerima  kerusakan setengah dari musuh."
            axia "Tch, aku spesial summon,  Ultimate  Lolibaba, Kanna Kamui !!!!"
            axia "Lalu aku akan korbankan Renge dengan menggunakan skill Kanna."
            axia "Aku summon, Dragon Kanna ke battlefield !"
            axia "Dengan Attack 2500 aku akan menghancurkan kuda nil sialan mu itu !"
            axia "Kanna serang dia !"
            rian "Sayang sekali... Aku aktifkan kartu ku !"
            rian "Panci Emak !"
            rian "Dengan panci itu aku menepis serangan naga mu !"
            axia "Sialan! Kau selamat kali ini."
            axia "Tapi di giliran berikutnya adalah kemenangan ku !"
            rian "Mari kita lihat saja, Edy."
            rian "Aku akan menyelesaikan ini tanpa kekalahan !"
            rian "Draw !"
            rian "Keluarlah ! Hiu Jawa !"
            rian "Hiu Jawa dengan attack 1000 memiliki efek yang menyeramkan."
            rian "Aku aktifkan, Gigi Hiu !"
            rian "Dengan menggunakan Gigi Hiu, aku mengurangi attack dari Kanna sebesar 2000."
            rian "Dengan begitu aku akan menggunakan kartu spell ku, aktiflah ! FBI !"
            rian "Dengan begitu para loli mu akan terkirim ke kuburan."
            rian "Lalu aku-"
            axia "Ckckck... Tidak secepat itu anak muda."
            axia "Aku lakukan Chain Card, dan mengaktifkan{w} Zoo Hunter !"
            axia "Dengan begitu semua tipe binatang milikmu akan hancur dan dikirim ke kuburan."
            axia "Hahaha... Sekarang bagaimana Rian ? Apakah kamu mau menyerah saja ?"
            axia "Karena nasib mu sudah ada di tanganku ! Maka kau sudah tamat."
            rian "Jika nasib ku berada di tanganmu, aku akan merebutnya kembali !"
            rian "Aktifkan Fatanil dari kuburan !"
            rian "Aku akan menggabungkannya dengan Cyber Dragon !"
            rian "Datanglah ! Mecha Fatanil !"
            rian "Tidak hanya itu saja ! Munculah ! Ksatria Hitam !"
            rian "Manusia Kecoa Terbang !"
            rian "Dengan Attack 2500 ditambah oleh Mecha Fatanil serangan mereka menjadi 8000 !"
            rian "Dengan ini, berakhirlah sudah, Edy !"
            rian "Aku akan melawan takdir. Dan aku akan menang !"
            rian "Serang !"
            "Axiaregis menerima serangan fatal, tapi sayangnya darahnya hanya berkurang setengah."
            axia "HAHAHAHA... Kau salah perhitungan bocah !"
            axia "Aktifkan Kanna dari kuburan, mengurangi damage yang kuterima jadi setengah."
            axia "Sekarang giliranku."
            rian "Kata siapa ?"
            axia "Tidak mungkin ??"
            rian "Aku aktifkan efek dari manusia kecoa terbang."
            rian "Menambahkan jumlah serangan yang kamu terima."
            rian "Sekarang nyawamu tersisa 2000."
            rian "Sebaiknya kamu hitung dosa-dosamu !"
            axia "Hahahaha... Dosa? Seharusnya kamu lihat kembali posisimu."
            axia "Sekarang giliranku."
            axia "Draw !"
            axia "Hmmm, aku summon, Senko !"
            axia "Dengan munculnya Senko, aku akan menghidupkan kembali..."
            axia "Kanna Dragon !"
            axia "Lalu serangannya akan menjadi 6000 dengan efek dari Kanna loli di kuburan."
            axia "Sekarang kau tak akan bisa berbuat apa-apa... KAU KALAH RI-"
            "Rian menarik tanganku dan langsung lari dari hadapan Axiaregis."
            axia "TUNGGU ! WOI !"
            axia "ANYEEEE JANGAN TINGGALKAN AKU LAGIII !!!"
            axia "ANYEEEEEEEEEE !!!"
            "Rian terus berlari tanpa peduli dengan teriakan Axiaregis, aku yang masih tidak mengerti dengan mereka hanya bisa diam membisu."
            rian "Yuur, aku harap kamu lari sekarang juga."
            y "Bagaimana denganmu ? Kenapa kita tidak lari bersama saja ?"
            rian "Tidak bisa... Aku harus menghentikan manusia NPD itu."
            rian "Tenang saja, aku akan baik-baik saja."
            rian "Selama dirimu bisa tersenyum, semuanya akan baik-baik saja."
            rian "Jadi... Tersenyumlah ! Dan pergi kemanapun yang kamu mau."
            rian "Karena Yuura yang aku kenal selalu tersenyum."
            y "B-baiklah… Tapi kamu hati-hati, oke ? Dia terlalu berbahaya."
            rian "Tenang saja... Aku dan pasukan hewanku tak akan kalah !"
            "Dia melempar banyak sekali bola dan mengeluarkan seluruh hewan yang ada di penginapan ini."
            rian "Larilah ! Si NPD sudah datang !"
            "Axiaregis datang dengan kecepatan penuh, dia membawa seluruh pasukan anak kecil yang jumlahnya ada ratusan. Membuatku tak punya pilihan lain selain lari lagi."
            "Pada titik ini aku sudah sangat muak, mengapa diriku hanya berlari terus menerus. Apa aku tak bisa melakukan apapun seperti Yuura yang mereka kenal ?"
            "Apa aku hanya akan terus seperti ini sampai aku menemukan jalan keluarnya ? Aku sudah sangat lelah dan ingin segera pergi dari tempat ini."

    return